#!/bin/sh
./target/release/blockchain-simulator --blockchain-state ./data/blockchain.json \
--inclusion-proof proof.json \
verify-inclusion-proof # For some reason the enum subcommand argument needs to come last
